name: Build and Release App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Zip output
      run: |
        cd dist
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          powershell Compress-Archive -Path mimicQuery.exe -DestinationPath mimicQuery-windows-${{ github.ref_name }}.zip
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          ditto -c -k --sequesterRsrc --keepParent mimicQuery.app mimicQuery-mac-${{ github.ref_name }}.zip
        else
          zip mimicQuery-linux-${{ github.ref_name }}.zip mimicQuery
        fi

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/mimicQuery-*-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
