name: Build and Release App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # needed for GitHub release uploads

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Zip output (Windows)
      if: runner.os == 'Windows'
      run: |
        powershell.exe Compress-Archive -Path dist\mimicQuery.exe -DestinationPath mimicQuery-windows-${{ github.ref_name }}.zip
        move mimicQuery-windows-${{ github.ref_name }}.zip dist\

    - name: Zip output (macOS or Linux)
      if: runner.os != 'Windows'
      run: |
        zip -r mimicQuery-${{ runner.os }}-${{ github.ref_name }}.zip dist/mimicQuery*
        mv mimicQuery-${{ runner.os }}-${{ github.ref_name }}.zip dist/

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/mimicQuery-*-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
